### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Biggitybaked** [HxnDev/Insta-Profile-Details#2]
What should the key be?

Traceback (most recent call last):
  File "/root/AllHackingTools/Insta-Profile-Details/main.py", line 7, in <module>
    user = InstagramUser(username)
  File "/usr/local/lib/python3.9/dist-packages/instagramy/InstagramUser.py", line 63, in __init__
    username, data["entry_data"]["ProfilePage"][0]["graphql"]["user"]
KeyError: 'ProfilePage'

**Comment by HxnDev** [comment]
Can you tell me how are you running and what exactly is the issue?
